# Redirect all HTTP → HTTPS
server {
    listen 80;
    server_name mylibrary.irfan-project.web.id;
    return 301 https://$host$request_uri;
}

# HTTPS Server
server {
    listen 443 ssl;
    server_name mylibrary.irfan-project.web.id;

    # SSL Certificates from Certbot
    ssl_certificate /etc/letsencrypt/live/mylibrary.irfan-project.web.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mylibrary.irfan-project.web.id/privkey.pem;

    index index.php index.html;
    root /var/www/html/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
